name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code từ repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Thiết lập Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # 3. Cài đặt dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Chạy tests (nếu có)
    - name: Run tests
      run: |
        python ${{ github.workspace }}/my_tennis_club/manage.py test

    # 5. Deploy lên server
    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Tạo thư mục .ssh nếu chưa tồn tại
        mkdir -p ~/.ssh

        # Thêm khóa công khai của máy chủ vào known_hosts
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts


        scp -i private_key.pem -r . $USER@$HOST:/dut/test/test_deploy_django
        ssh -i private_key.pem $USER@$HOST << 'EOF'
          cd /dut/test/test_deploy_django
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart gunicorn
          systemctl restart nginx
        EOF
